<?php

return [
    'AED' => ['name' => 'UAE Dirham', 'symbol' => 'د.إ'],
    'AFN' => ['name' => 'Afghan Afghani', 'symbol' => '؋'],
    'ALL' => ['name' => 'Albanian Lek', 'symbol' => 'L'],
    'AMD' => ['name' => 'Armenian Dram', 'symbol' => '֏'],
    'ANG' => ['name' => 'Netherlands Antillean Guilder', 'symbol' => 'ƒ'],
    'AOA' => ['name' => 'Angolan Kwanza', 'symbol' => 'Kz'],
    'ARS' => ['name' => 'Argentine Peso', 'symbol' => '$'],
    'AUD' => ['name' => 'Australian Dollar', 'symbol' => 'A$'],
    'AWG' => ['name' => 'Aruban Florin', 'symbol' => 'ƒ'],
    'AZN' => ['name' => 'Azerbaijani Manat', 'symbol' => '₼'],
    'BAM' => ['name' => 'Bosnia-Herzegovina Convertible Mark', 'symbol' => 'KM'],
    'BBD' => ['name' => 'Barbadian Dollar', 'symbol' => '$'],
    'BDT' => ['name' => 'Bangladeshi Taka', 'symbol' => '৳'],
    'BGN' => ['name' => 'Bulgarian Lev', 'symbol' => 'лв'],
    'BHD' => ['name' => 'Bahraini Dinar', 'symbol' => '.د.ب'],
    'BIF' => ['name' => 'Burundian Franc', 'symbol' => 'FBu'],
    'BMD' => ['name' => 'Bermudan Dollar', 'symbol' => '$'],
    'BND' => ['name' => 'Brunei Dollar', 'symbol' => '$'],
    'BOB' => ['name' => 'Bolivian Boliviano', 'symbol' => 'Bs'],
    'BOV' => ['name' => 'Bolivian Mvdol', 'symbol' => 'BOV'],
    'BRL' => ['name' => 'Brazilian Real', 'symbol' => 'R$'],
    'BSD' => ['name' => 'Bahamian Dollar', 'symbol' => '$'],
    'BTN' => ['name' => 'Bhutanese Ngultrum', 'symbol' => 'Nu.'],
    'BWP' => ['name' => 'Botswanan Pula', 'symbol' => 'P'],
    'BYN' => ['name' => 'Belarusian Ruble', 'symbol' => 'Br'],
    'BZD' => ['name' => 'Belize Dollar', 'symbol' => 'BZ$'],
    'CAD' => ['name' => 'Canadian Dollar', 'symbol' => 'C$'],
    'CDF' => ['name' => 'Congolese Franc', 'symbol' => 'FC'],
    'CHE' => ['name' => 'WIR Euro', 'symbol' => 'CHE'],
    'CHF' => ['name' => 'Swiss Franc', 'symbol' => 'Fr'],
    'CHW' => ['name' => 'WIR Franc', 'symbol' => 'CHW'],
    'CLF' => ['name' => 'Chilean Unit of Account', 'symbol' => 'CLF'],
    'CLP' => ['name' => 'Chilean Peso', 'symbol' => '$'],
    'CNY' => ['name' => 'Chinese Yuan', 'symbol' => '¥'],
    'COP' => ['name' => 'Colombian Peso', 'symbol' => '$'],
    'COU' => ['name' => 'Colombian Real Value Unit', 'symbol' => 'COU'],
    'CRC' => ['name' => 'Costa Rican Colón', 'symbol' => '₡'],
    'CUC' => ['name' => 'Cuban Convertible Peso', 'symbol' => '$'],
    'CUP' => ['name' => 'Cuban Peso', 'symbol' => '$'],
    'CVE' => ['name' => 'Cape Verdean Escudo', 'symbol' => '$'],
    'CZK' => ['name' => 'Czech Koruna', 'symbol' => 'Kč'],
    'DJF' => ['name' => 'Djiboutian Franc', 'symbol' => 'Fdj'],
    'DKK' => ['name' => 'Danish Krone', 'symbol' => 'kr'],
    'DOP' => ['name' => 'Dominican Peso', 'symbol' => 'RD$'],
    'DZD' => ['name' => 'Algerian Dinar', 'symbol' => 'دج'],
    'EGP' => ['name' => 'Egyptian Pound', 'symbol' => 'E£'],
    'ERN' => ['name' => 'Eritrean Nakfa', 'symbol' => 'Nfk'],
    'ETB' => ['name' => 'Ethiopian Birr', 'symbol' => 'Br'],
    'EUR' => ['name' => 'Euro', 'symbol' => '€'],
    'FJD' => ['name' => 'Fijian Dollar', 'symbol' => '$'],
    'FKP' => ['name' => 'Falkland Islands Pound', 'symbol' => '£'],
    'GBP' => ['name' => 'British Pound Sterling', 'symbol' => '£'],
    'GEL' => ['name' => 'Georgian Lari', 'symbol' => '₾'],
    'GHS' => ['name' => 'Ghanaian Cedi', 'symbol' => '₵'],
    'GIP' => ['name' => 'Gibraltar Pound', 'symbol' => '£'],
    'GMD' => ['name' => 'Gambian Dalasi', 'symbol' => 'D'],
    'GNF' => ['name' => 'Guinean Franc', 'symbol' => 'FG'],
    'GTQ' => ['name' => 'Guatemalan Quetzal', 'symbol' => 'Q'],
    'GYD' => ['name' => 'Guyanaese Dollar', 'symbol' => '$'],
    'HKD' => ['name' => 'Hong Kong Dollar', 'symbol' => 'HK$'],
    'HNL' => ['name' => 'Honduran Lempira', 'symbol' => 'L'],
    'HRK' => ['name' => 'Croatian Kuna', 'symbol' => 'kn'],
    'HTG' => ['name' => 'Haitian Gourde', 'symbol' => 'G'],
    'HUF' => ['name' => 'Hungarian Forint', 'symbol' => 'Ft'],
    'IDR' => ['name' => 'Indonesian Rupiah', 'symbol' => 'Rp'],
    'ILS' => ['name' => 'Israeli New Sheqel', 'symbol' => '₪'],
    'INR' => ['name' => 'Indian Rupee', 'symbol' => '₹'],
    'IQD' => ['name' => 'Iraqi Dinar', 'symbol' => 'ع.د'],
    'IRR' => ['name' => 'Iranian Rial', 'symbol' => '﷼'],
    'ISK' => ['name' => 'Icelandic Króna', 'symbol' => 'kr'],
    'JMD' => ['name' => 'Jamaican Dollar', 'symbol' => 'J$'],
    'JOD' => ['name' => 'Jordanian Dinar', 'symbol' => 'JD'],
    'JPY' => ['name' => 'Japanese Yen', 'symbol' => '¥'],
    'KES' => ['name' => 'Kenyan Shilling', 'symbol' => 'KSh'],
    'KGS' => ['name' => 'Kyrgystani Som', 'symbol' => 'лв'],
    'KHR' => ['name' => 'Cambodian Riel', 'symbol' => '៛'],
    'KMF' => ['name' => 'Comorian Franc', 'symbol' => 'CF'],
    'KPW' => ['name' => 'North Korean Won', 'symbol' => '₩'],
    'KRW' => ['name' => 'South Korean Won', 'symbol' => '₩'],
    'KWD' => ['name' => 'Kuwaiti Dinar', 'symbol' => 'KD'],
    'KYD' => ['name' => 'Cayman Islands Dollar', 'symbol' => '$'],
    'KZT' => ['name' => 'Kazakhstani Tenge', 'symbol' => '₸'],
    'LAK' => ['name' => 'Laotian Kip', 'symbol' => '₭'],
    'LBP' => ['name' => 'Lebanese Pound', 'symbol' => '£'],
    'LKR' => ['name' => 'Sri Lankan Rupee', 'symbol' => '₨'],
    'LRD' => ['name' => 'Liberian Dollar', 'symbol' => '$'],
    'LSL' => ['name' => 'Lesotho Loti', 'symbol' => 'M'],
    'LYD' => ['name' => 'Libyan Dinar', 'symbol' => 'LD'],
    'MAD' => ['name' => 'Moroccan Dirham', 'symbol' => 'MAD'],
    'MDL' => ['name' => 'Moldovan Leu', 'symbol' => 'MDL'],
    'MGA' => ['name' => 'Malagasy Ariary', 'symbol' => 'Ar'],
    'MKD' => ['name' => 'Macedonian Denar', 'symbol' => 'ден'],
    'MMK' => ['name' => 'Myanma Kyat', 'symbol' => 'K'],
    'MNT' => ['name' => 'Mongolian Tugrik', 'symbol' => '₮'],
    'MOP' => ['name' => 'Macanese Pataca', 'symbol' => 'MOP$'],
    'MRU' => ['name' => 'Mauritanian Ouguiya', 'symbol' => 'UM'],
    'MUR' => ['name' => 'Mauritian Rupee', 'symbol' => '₨'],
    'MVR' => ['name' => 'Maldivian Rufiyaa', 'symbol' => 'Rf'],
    'MWK' => ['name' => 'Malawian Kwacha', 'symbol' => 'MK'],
    'MXN' => ['name' => 'Mexican Peso', 'symbol' => '$'],
    'MXV' => ['name' => 'Mexican Investment Unit', 'symbol' => 'MXV'],
    'MYR' => ['name' => 'Malaysian Ringgit', 'symbol' => 'RM'],
    'MZN' => ['name' => 'Mozambican Metical', 'symbol' => 'MT'],
    'NAD' => ['name' => 'Namibian Dollar', 'symbol' => 'N$'],
    'NGN' => ['name' => 'Nigerian Naira', 'symbol' => '₦'],
    'NIO' => ['name' => 'Nicaraguan Córdoba', 'symbol' => 'C$'],
    'NOK' => ['name' => 'Norwegian Krone', 'symbol' => 'kr'],
    'NPR' => ['name' => 'Nepalese Rupee', 'symbol' => '₨'],
    'NZD' => ['name' => 'New Zealand Dollar', 'symbol' => '$'],
    'OMR' => ['name' => 'Omani Rial', 'symbol' => '﷼'],
    'PAB' => ['name' => 'Panamanian Balboa', 'symbol' => 'B/.'],
    'PEN' => ['name' => 'Peruvian Nuevo Sol', 'symbol' => 'S/.'],
    'PGK' => ['name' => 'Papua New Guinean Kina', 'symbol' => 'K'],
    'PHP' => ['name' => 'Philippine Peso', 'symbol' => '₱'],
    'PKR' => ['name' => 'Pakistani Rupee', 'symbol' => '₨'],
    'PLN' => ['name' => 'Polish Złoty', 'symbol' => 'zł'],
    'PYG' => ['name' => 'Paraguayan Guarani', 'symbol' => '₲'],
    'QAR' => ['name' => 'Qatari Rial', 'symbol' => '﷼'],
    'RON' => ['name' => 'Romanian Leu', 'symbol' => 'lei'],
    'RSD' => ['name' => 'Serbian Dinar', 'symbol' => 'din'],
    'RUB' => ['name' => 'Russian Ruble', 'symbol' => '₽'],
    'RWF' => ['name' => 'Rwandan Franc', 'symbol' => 'RF'],
    'SAR' => ['name' => 'Saudi Riyal', 'symbol' => '﷼'],
    'SBD' => ['name' => 'Solomon Islands Dollar', 'symbol' => '$'],
    'SCR' => ['name' => 'Seychellois Rupee', 'symbol' => '₨'],
    'SDG' => ['name' => 'Sudanese Pound', 'symbol' => 'ج.س.'],
    'SEK' => ['name' => 'Swedish Krona', 'symbol' => 'kr'],
    'SGD' => ['name' => 'Singapore Dollar', 'symbol' => '$'],
    'SHP' => ['name' => 'Saint Helena Pound', 'symbol' => '£'],
    'SLE' => ['name' => 'Sierra Leonean Leone', 'symbol' => 'Le'],
    'SOS' => ['name' => 'Somali Shilling', 'symbol' => 'S'],
    'SRD' => ['name' => 'Surinamese Dollar', 'symbol' => '$'],
    'SSP' => ['name' => 'South Sudanese Pound', 'symbol' => '£'],
    'STN' => ['name' => 'São Tomé and Príncipe Dobra', 'symbol' => 'Db'],
    'SVC' => ['name' => 'Salvadoran Colón', 'symbol' => '$'],
    'SYP' => ['name' => 'Syrian Pound', 'symbol' => '£'],
    'SZL' => ['name' => 'Swazi Lilangeni', 'symbol' => 'E'],
    'THB' => ['name' => 'Thai Baht', 'symbol' => '฿'],
    'TJS' => ['name' => 'Tajikistani Somoni', 'symbol' => 'SM'],
    'TMT' => ['name' => 'Turkmenistani Manat', 'symbol' => 'T'],
    'TND' => ['name' => 'Tunisian Dinar', 'symbol' => 'د.ت'],
    'TOP' => ['name' => 'Tongan Paʻanga', 'symbol' => 'T$'],
    'TRY' => ['name' => 'Turkish Lira', 'symbol' => '₺'],
    'TTD' => ['name' => 'Trinidad and Tobago Dollar', 'symbol' => 'TT$'],
    'TWD' => ['name' => 'New Taiwan Dollar', 'symbol' => 'NT$'],
    'TZS' => ['name' => 'Tanzanian Shilling', 'symbol' => 'TSh'],
    'UAH' => ['name' => 'Ukrainian Hryvnia', 'symbol' => '₴'],
    'UGX' => ['name' => 'Ugandan Shilling', 'symbol' => 'USh'],
    'USD' => ['name' => 'US Dollar', 'symbol' => '$'],
    'USN' => ['name' => 'US Dollar (Next day)', 'symbol' => '$'],
    'UYI' => ['name' => 'Uruguayan Peso en Unidades Indexadas', 'symbol' => 'UYI'],
    'UYU' => ['name' => 'Uruguayan Peso', 'symbol' => '$U'],
    'UYW' => ['name' => 'Unidad Previsional', 'symbol' => 'UP'],
    'UZS' => ['name' => 'Uzbekistan Som', 'symbol' => 'лв'],
    'VED' => ['name' => 'Venezuelan Bolívar Soberano', 'symbol' => 'Bs.S'],
    'VES' => ['name' => 'Venezuelan Bolívar Soberano', 'symbol' => 'Bs.S'],
    'VND' => ['name' => 'Vietnamese Dong', 'symbol' => '₫'],
    'VUV' => ['name' => 'Vanuatu Vatu', 'symbol' => 'VT'],
    'WST' => ['name' => 'Samoan Tala', 'symbol' => 'WS$'],
    'XAF' => ['name' => 'CFA Franc BEAC', 'symbol' => 'FCFA'],
    'XAG' => ['name' => 'Silver Ounce', 'symbol' => 'oz'],
    'XAU' => ['name' => 'Gold Ounce', 'symbol' => 'oz'],
    'XBA' => ['name' => 'European Composite Unit', 'symbol' => 'XBA'],
    'XBB' => ['name' => 'European Monetary Unit', 'symbol' => 'XBB'],
    'XBC' => ['name' => 'European Unit of Account 9', 'symbol' => 'XBC'],
    'XBD' => ['name' => 'European Unit of Account 17', 'symbol' => 'XBD'],
    'XCD' => ['name' => 'East Caribbean Dollar', 'symbol' => '$'],
    'XDR' => ['name' => 'Special Drawing Rights', 'symbol' => 'SDR'],
    'XOF' => ['name' => 'CFA Franc BCEAO', 'symbol' => 'CFA'],
    'XPD' => ['name' => 'Palladium Ounce', 'symbol' => 'oz'],
    'XPF' => ['name' => 'CFP Franc', 'symbol' => '₣'],
    'XPT' => ['name' => 'Platinum Ounce', 'symbol' => 'oz'],
    'XSU' => ['name' => 'Sucre', 'symbol' => 'XSU'],
    'XTS' => ['name' => 'Testing Currency Code', 'symbol' => 'XTS'],
    'XUA' => ['name' => 'ADB Unit of Account', 'symbol' => 'XUA'],
    'XXX' => ['name' => 'Unknown Currency', 'symbol' => 'XXX'],
    'YER' => ['name' => 'Yemeni Rial', 'symbol' => '﷼'],
    'ZAR' => ['name' => 'South African Rand', 'symbol' => 'R'],
    'ZMW' => ['name' => 'Zambian Kwacha', 'symbol' => 'ZK'],
    'ZWL' => ['name' => 'Zimbabwean Dollar', 'symbol' => 'Z$'],
]; 